sqlprinter:
  show: true
  filter:
    - com.github.dreamroute.sqlprinter.boot.mapper.UserMapper.selectById
    - com.github.dreamroute.sqlprinter.boot.mapper.UserMapper.selectByIds
  show-result: true
mybatis:
  mapper-locations: /mapper/*
  type-handlers-package: com.github.dreamroute.mybatis.pro.base.typehandler
  pro:
    delete-use-update: false